routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PostController@index");

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// User Panel
Route::group([
    'middleware'    => ['auth'],
    'prefix'        => 'panel',
    'namespace'     => 'Panel',
    'as'            => 'panel.'
], function() {

    Route::resource('posts', 'PostController');

    Route::resource('comments', 'CommentController');
});

Route::get('posts', 'PostController@index')->name('posts.index');
Route::get('posts/top/{count}', 'PostController@getTops')->name('posts.get_tops');
Route::get('posts/{slug}', 'PostController@show')->name('posts.show');

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Scopes\OrderScope;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    /**
     * The name of the "updated at" column.
     *
     * @var string
     */
    const UPDATED_AT = null;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'body', 'user_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'id'
    ];

    /**
     * The attributes that should be visible in arrays.
     *
     * @var array
     */
    // protected $visible = [];

    protected $appends = ['slug'];


    protected static function boot() {
        parent::boot();
        static::addGlobalScope(new OrderScope('id', 'desc'));
    }


    /**
     * --------------------------------------------------------------------------
     * SCOPE
     * --------------------------------------------------------------------------
     */
    public function scopeDetail($q)
    {
        return $q->with(['comments.author', 'author']);
    }

    /**
     * --------------------------------------------------------------------------
     * RELATIONS
     * --------------------------------------------------------------------------
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     *  --------------------------------------------------------------------------
     *  ACCESORS
     *  --------------------------------------------------------------------------
     */
    public function getSlugAttribute()
    {
        return $this->id . "-" . str_replace(" ", "-", $this->title);
    }

    public function getDateAttribute()
    {
        return dateFormat($this->created_at, 'Y-m-d');
    }

}

app/Http/Controllers/Panel/CommentController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Requests\Comments\StoreCommentRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Comments\StoreCommentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCommentRequest $request)
    {
        $data = $request->validated();

        $user = auth()->user();
        $user->comments()->create($data);

        return back()->withMessage('success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Panel/PostController.php
<?php

namespace App\Http\Controllers\Panel;


use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\Posts\StorePostRequest;
use function Sodium\compare;

class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("panel.posts.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param    $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $validated = $request->validated();
        $user = auth()->user();
        $user->posts()->create($validated);
        //Cache::forgot('posts-10')

        return back()->withMessage('success');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class PostController extends Controller
{
    const POST_PER_PAGE = 5;
    const TOP_COUNT = 10;

    public function index()
    {
        $posts = Post::with(['author'])->paginate(self::POST_PER_PAGE);

        return view("front.posts.index", compact('posts'));
    }

    public function show($slug)
    {
        $id = explode('-', $slug)[0];
        $post = Post::detail()->findOrFail($id);

        return view('front.posts.show', compact('post'));
    }

    public function getTops($count = self::TOP_COUNT)
    {
//        $posts = Cache::rememberForever('posts-10', function() use($count)
//        {
//            return Post::detail()->take($count)->get();
//        });


        $posts = Post::detail()->take($count)->get();

        $top = true;

        return view("front.posts.index", compact('posts', 'top'));
    }


}

resources/views/panel/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {!! displayAlert() !!}
                {!! displayErrors($errors) !!}
                <div class="card">
                    <div class="card-header">{{ __('Create Post') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('panel.posts.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="body" class="col-md-4 col-form-label text-md-right">Body</label>

                                <div class="col-md-6">
                                    <textarea class="form-control @error('title') is-invalid @enderror" id="body" name="body">

                                    </textarea>
                                    @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection