routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PostController@index");

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// User Panel
Route::group([
    'middleware'    => ['auth'],
    'prefix'        => 'panel',
    'namespace'     => 'Panel',
    'as'            => 'panel.'
], function() {

    Route::resource('posts', 'PostController');

    Route::resource('comments', 'CommentController');
});

Route::get('posts', 'PostController@index')->name('posts.index');
Route::get('posts/top/{count}', 'PostController@getTops')->name('posts.get_tops');
Route::get('posts/{slug}', 'PostController@show')->name('posts.show');

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Scopes\OrderScope;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    /**
     * The name of the "updated at" column.
     *
     * @var string
     */
    const UPDATED_AT = null;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'body', 'user_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'id'
    ];

    /**
     * The attributes that should be visible in arrays.
     *
     * @var array
     */
    // protected $visible = [];

    protected $appends = ['slug'];


    protected static function boot() {
        parent::boot();
        static::addGlobalScope(new OrderScope('id', 'desc'));
    }


    /**
     * --------------------------------------------------------------------------
     * SCOPE
     * --------------------------------------------------------------------------
     */
    public function scopeDetail($q)
    {
        return $q->with(['comments.author', 'author']);
    }

    /**
     * --------------------------------------------------------------------------
     * RELATIONS
     * --------------------------------------------------------------------------
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     *  --------------------------------------------------------------------------
     *  ACCESORS
     *  --------------------------------------------------------------------------
     */
    public function getSlugAttribute()
    {
        return $this->id . "-" . str_replace(" ", "-", $this->title);
    }

    public function getDateAttribute()
    {
        return dateFormat($this->created_at, 'Y-m-d');
    }

}

app/Http/Controllers/Panel/PostController.php
<?php

namespace App\Http\Controllers\Panel;


use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\Posts\StorePostRequest;
use function Sodium\compare;

class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("panel.posts.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param    $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $validated = $request->validated();
        $user = auth()->user();
        $user->posts()->create($validated);
        //Cache::forgot('posts-10')

        return back()->withMessage('success');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class PostController extends Controller
{
    const POST_PER_PAGE = 5;
    const TOP_COUNT = 10;

    public function index()
    {
        $posts = Post::with(['author'])->paginate(self::POST_PER_PAGE);

        return view("front.posts.index", compact('posts'));
    }

    public function show($slug)
    {
        $id = explode('-', $slug)[0];
        $post = Post::detail()->findOrFail($id);

        return view('front.posts.show', compact('post'));
    }

    public function getTops($count = self::TOP_COUNT)
    {
//        $posts = Cache::rememberForever('posts-10', function() use($count)
//        {
//            return Post::detail()->take($count)->get();
//        });


        $posts = Post::detail()->take($count)->get();

        $top = true;

        return view("front.posts.index", compact('posts', 'top'));
    }


}

resources/views/front/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @foreach($posts as $post)
                    <div class="card mt-2">
                        <div class="card-header"><a href="{{route('posts.show', $post->slug)}}">{{ $post->title }}</a></div>
                        <div class="card-body">
                            {{ $post->body }}
                            <div>
                                <ul>
                                    <li><small>author: {{$post->author->name}}</small></li>
                                </ul>
                            </div>
                        </div>

                        @if(isset($top) And $top == true)
                            @foreach($post->comments as $comment)
                                <div class="col-md-10">
                                    <div class="card mt-2">

                                        <div class="card-header">author: {{$comment->author->name}}   <small>{{$comment->date}}</small></div>
                                        <div class="card-body">
                                            {{ $comment->body }}
                                        </div>
                                    </div>
                                </div>

                            @endforeach
                        @endif


                    </div>
                @endforeach
                    @if ($posts instanceof \Illuminate\Pagination\LengthAwarePaginator)
                        {{ $posts->onEachSide(5)->links() }}
                    @endif
            </div>
        </div>
    </div>
@endsection

resources/views/front/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <!--Modal: Login / Register Form-->
    <div class="modal fade" id="modalLRForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog cascading-modal" role="document">
            <!--Content-->
            <div class="modal-content">

                <!--Modal cascading tabs-->
                <div class="modal-c-tabs">

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs md-tabs tabs-2 light-blue darken-3" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#panel7" role="tab"><i class="fas fa-user mr-1"></i>
                                Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#panel8" role="tab"><i class="fas fa-user-plus mr-1"></i>
                                Register</a>
                        </li>
                    </ul>

                    <!-- Tab panels -->
                    <div class="tab-content">
                        <!--Panel 7-->
                        <div class="tab-pane fade in show active" id="panel7" role="tabpanel">

                            <form action="{{ route('login') }}" method="POST">
                                @csrf
                                <div class="modal-body mb-1">
                                    <div class="md-form form-sm mb-5">
                                        <i class="fas fa-envelope prefix"></i>
                                        <input type="email" name="email" id="modalLRInput10" class="form-control form-control-sm validate">
                                        <label data-error="wrong" data-success="right" for="modalLRInput10">Your email</label>
                                    </div>

                                    <div class="md-form form-sm mb-4">
                                        <i class="fas fa-lock prefix"></i>
                                        <input type="password" name="password" id="modalLRInput11" class="form-control form-control-sm validate">
                                        <label data-error="wrong" data-success="right" for="modalLRInput11">Your password</label>
                                    </div>
                                    <div class="text-center mt-2">
                                        <button type="submit" class="btn btn-info">Log in <i class="fas fa-sign-in ml-1"></i></button>
                                    </div>

                                </div>
                            </form>

                            <!--Footer-->
                            <div class="modal-footer">
                                <div class="options text-center text-md-right mt-1">
                                    <p>Not a member? <a href="#" class="blue-text">Sign Up</a></p>
                                </div>
                                <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Close</button>
                            </div>

                        </div>
                        <!--/.Panel 7-->

                        <!--Panel 8-->
                        <div class="tab-pane fade" id="panel8" role="tabpanel">

                            <!--Body-->
                            <form action="{{ route('register') }}" method="POST">
                                @csrf
                                <div class="modal-body">
                                    <div class="md-form form-sm mb-5">
                                        <i class="fas fa-envelope prefix"></i>
                                        <input type="text" name="name" id="modalLRInput12" class="form-control form-control-sm validate">
                                        <label data-error="wrong" data-success="right" for="modalLRInput12">name</label>
                                    </div>
                                    <div class="md-form form-sm mb-5">
                                        <i class="fas fa-envelope prefix"></i>
                                        <input type="email" name="email" id="modalLRInput12" class="form-control form-control-sm validate">
                                        <label data-error="wrong" data-success="right" for="modalLRInput12">Your email</label>
                                    </div>

                                    <div class="md-form form-sm mb-5">
                                        <i class="fas fa-lock prefix"></i>
                                        <input type="password" name="password" id="modalLRInput13" class="form-control form-control-sm validate">
                                        <label data-error="wrong" data-success="right" for="modalLRInput13">Your password</label>
                                    </div>

                                    <div class="md-form form-sm mb-4">
                                        <i class="fas fa-lock prefix"></i>
                                        <input type="password" name="password_confirmation" id="modalLRInput14" class="form-control form-control-sm validate">
                                        <label data-error="wrong" data-success="right" for="modalLRInput14">Repeat password</label>
                                    </div>

                                    <div class="text-center form-sm mt-2">
                                        <button class="btn btn-info">Sign up <i class="fas fa-sign-in ml-1"></i></button>
                                    </div>

                                </div>
                            </form>
                            <!--Footer-->
                            <div class="modal-footer">
                                <div class="options text-right">
                                    <p class="pt-1">Already have an account? <a href="#" class="blue-text">Log In</a></p>
                                </div>
                                <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                        <!--/.Panel 8-->
                    </div>

                </div>
            </div>
            <!--/.Content-->
        </div>
    </div>
    <!--Modal: Login / Register Form-->
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-8">
                {!! displayAlert() !!}
                {!! displayErrors($errors) !!}
                <div class="card mt-2">
                    <div class="card-header">{{ $post->title }}</div>
                    <div class="card-body">
                        {{ $post->body }}
                        <div>
                            <ul>
                                <li><small>author: {{$post->author->name}}</small></li>
                            </ul>
                        </div>
                    </div>

                </div>
                <h2 class="mt-3">Comments</h2>
                @foreach($post->comments as $comment)

                    <div class="card mt-2">

                        <div class="card-header">author: {{$comment->author->name}}   <small>{{$comment->date}}</small></div>
                        <div class="card-body">
                            {{ $comment->body }}
                        </div>
                    </div>
                @endforeach

                <div class="card mt-2">
                    <div class="card-header">{{ __('Add Comment') }}</div>
                    <div class="card-body">
                        <form id="add_comment" method="POST" action="{{ route('panel.comments.store') }}">
                            @csrf
                            <input type="hidden" name="post_id" value="{{ $post->id }}">
                            <div class="form-group row">
                                <label for="body" class="col-md-4 col-form-label text-md-right">Body</label>

                                <div class="col-md-6">
                                    <textarea class="form-control @error('title') is-invalid @enderror" id="body" name="body">

                                    </textarea>
                                    @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button id="submit" type="submit" class="btn btn-primary @if(!auth()->check()) disable @endif"  @if(!auth()->check()) data-toggle="modal" data-target="#modalLRForm" @endif >
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>

    <script>

        $(document).ready(function() {
            $('#submit').click(function(e){
                if($(this).hasClass('disable')) {
                    e.preventDefault();
                    console.log($(this).data('target'));
                    $('#modalLRForm').trigger('click');
                    return true;
                }
                return true;
            })
        })
    </script>
@endsection